if ('function' === typeof importScripts) {
  // Import the workbox libraries using Google's CDN
  importScripts(
    'https://storage.googleapis.com/workbox-cdn/releases/3.5.0/workbox-sw.js'
  );

  // Only use workbox functions if it was able to load properly
  if (workbox) {
    console.log('Workbox has loaded successfully. :)');

    // Configure workbox settings
    workbox.core.setLogLevel(workbox.core.LOG_LEVELS.debug);

    // Customize the names of the caches generated by workbox
    workbox.core.setCacheNameDetails({
      prefix: 'hidden-gems'
    });

    // This is where the precache manifest files will be injected
    // by workbox when the new service worker file is built
    workbox.precaching.precacheAndRoute([]);
  }
  else {
    console.log('Workbox failed to load. Thus, no offline functionality available. :(');
  }
}